In [10]:
from load_data import get_data

import numpy as np
import time
train, train_label, test, test_label = get_data()

In [49]:
# forward propagation
def sg(X):
    return 1/(1+np.exp(-X))    
def drelu(X):
    return np.where(X>0, 1, 0)

[[ 0.19975836 -0.39766557 -0.08594401  0.19440016 -0.08582073]
 [-0.45004654  0.03589641  0.16379465  0.01488911  0.44459476]
 [ 0.08655504  0.40340192 -0.3625253  -0.36072365  0.30739129]
 [-0.10232316 -0.3346458   0.42750858 -0.15223414  0.2508121 ]
 [ 0.22599799  0.38330609  0.12367221  0.25094243 -0.15110166]]
[[1 0 0 1 0]
 [0 1 1 1 1]
 [1 1 0 0 1]
 [0 0 1 0 1]
 [1 1 1 1 0]]


In [60]:
# forward

np.random.seed(1)

w_1 = np.random.random((4,3))

b_1 = np.random.random((4,1))
z_1 = np.dot(w_1, train)+ b_1
a_1 = np.maximum(z_1, 0)
w_2 = np.random.random((3,4))
b_2 = np.random.random((3, 1))
z_2 = np.dot(w_2, a_1)
a_2 = sg(z_2 )

In [61]:
# back propagation

dz_2 = a_2 - train_label
dw_2 = np.dot(dz_2,a_1.T)/524
db_1 = np.sum(dz_2, axis = 1, keepdims = True)
dz_1 = np.dot(w_2.T, dz_2)*drelu(z_1)
dw_1 = np.dot(dz_1, train.T)/524
db_1 = np.sum(dz_1, axis = 1, keepdims = True)






